from waterQualityPrediction.components.data_ingestion import DataIngestion
from waterQualityPrediction.components.data_transformation import DataTransformation
from waterQualityPrediction.components.model_trainer import ModelTrainer
from waterQualityPrediction.components.model_evaluation import ModelEvaluation