artifacts_root: artifacts


data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://water33.s3.amazonaws.com/water_potability.csv
  local_data_file: artifacts/data_ingestion/water_potability.csv
  
  
  
  # local_data_file: artifacts/data_ingestion/data.zip
  # unzip_dir: artifacts/data_ingestion